server:
  servlet:
    context-path:
  apiBasePath: /api/v
  apiVersion: 1
  apiPath: ${server.apiBasePath}${server.apiVersion}
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: none
#Security Configuration
security:
  wave:
    user:
      name: admin
      password: secret
      roles: USER,ADMIN,ACTUATOR
  authentication:
    type: HTTP_BASIC
    token:
      secret: with a value in an extension methods or authentication function will be considered
      token_prefix: Bearer
      header_string: Authorization
management:
  endpoints:
    web:
      base-path: /manage
#Logging Configuration
#Logging configuratuion is declared in log4j2-dev.yml
logging:
  config: classpath:log4j2.yaml